# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GemmaComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('archimate_id', models.CharField(max_length=100, unique=True, verbose_name='ArchiMate ID')),
                ('type', models.CharField(choices=[('applicatiecomponent', 'Applicatiecomponent'), ('applicatieservice', 'Applicatieservice'), ('applicatiefunctie', 'Applicatiefunctie'), ('anders', 'Anders')], default='applicatiecomponent', max_length=25, verbose_name='Type')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('gemma_online_url', models.URLField(blank=True, verbose_name='GEMMA Online URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='architectuur.gemmacomponent', verbose_name='Bovenliggend component')),
            ],
            options={
                'verbose_name': 'GEMMA component',
                'verbose_name_plural': 'GEMMA componenten',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='PakketGemmaComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('gemma_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakket_gemma', to='architectuur.gemmacomponent', verbose_name='GEMMA component')),
            ],
            options={
                'verbose_name': 'Pakket-GEMMA component',
                'verbose_name_plural': 'Pakket-GEMMA componenten',
            },
        ),
    ]
