# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architectuur', '0001_initial'),
        ('pakketten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakketgemmacomponent',
            name='pakket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakket_gemma', to='pakketten.pakket', verbose_name='Pakket'),
        ),
        migrations.AlterUniqueTogether(
            name='pakketgemmacomponent',
            unique_together={('pakket', 'gemma_component')},
        ),
    ]
