# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pakketten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standaard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('type', models.CharField(choices=[('verplicht', 'Verplicht (pas toe of leg uit)'), ('aanbevolen', 'Aanbevolen'), ('optioneel', 'Optioneel')], max_length=15, verbose_name='Type')),
                ('versie', models.CharField(blank=True, max_length=50, verbose_name='Versie')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('forum_standaardisatie_url', models.URLField(blank=True, verbose_name='Forum Standaardisatie URL')),
            ],
            options={
                'verbose_name': 'Standaard',
                'verbose_name_plural': 'Standaarden',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='PakketStandaard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('ondersteund', models.BooleanField(default=True, verbose_name='Ondersteund')),
                ('testrapport_url', models.URLField(blank=True, verbose_name='Testrapport URL')),
                ('pakket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakket_standaarden', to='pakketten.pakket', verbose_name='Pakket')),
                ('standaard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakket_standaarden', to='standaarden.standaard', verbose_name='Standaard')),
            ],
            options={
                'verbose_name': 'Pakket-standaard',
                'verbose_name_plural': 'Pakket-standaarden',
                'unique_together': {('pakket', 'standaard')},
            },
        ),
    ]
