# Generated by Django 5.1.15 on 2026-03-06 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificatie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('bericht', models.TextField(verbose_name='Bericht')),
                ('gelezen', models.BooleanField(default=False, verbose_name='Gelezen')),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
            ],
            options={
                'verbose_name': 'Notificatie',
                'verbose_name_plural': 'Notificaties',
                'ordering': ['-aangemaakt_op'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mailadres')),
                ('naam', models.CharField(max_length=255, verbose_name='Volledige naam')),
                ('rol', models.CharField(choices=[('publiek', 'Publiek'), ('aanbod_raadpleger', 'Aanbod-raadpleger'), ('gebruik_raadpleger', 'Gebruik-raadpleger'), ('aanbod_beheerder', 'Aanbod-beheerder'), ('gebruik_beheerder', 'Gebruik-beheerder'), ('ibd_beheerder', 'IBD-beheerder'), ('gt_inkoop_beheerder', 'GT Inkoop-beheerder'), ('functioneel_beheerder', 'Functioneel beheerder')], default='aanbod_raadpleger', max_length=30, verbose_name='Rol')),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('inactief', 'Inactief'), ('wacht_op_fiattering', 'Wacht op fiattering')], default='wacht_op_fiattering', max_length=25, verbose_name='Status')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='2FA ingeschakeld')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Gebruiker',
                'verbose_name_plural': 'Gebruikers',
                'ordering': ['-aangemaakt_op'],
            },
        ),
    ]
