# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gebruikers', '0001_initial'),
        ('organisaties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gebruikers', to='organisaties.organisatie', verbose_name='Organisatie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='notificatie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaties', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker'),
        ),
    ]
