# Generated by Django 5.1.15 on 2026-03-06 10:12

import apps.documenten.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('type', models.CharField(choices=[('dpia', 'DPIA'), ('verwerkersovereenkomst', 'Verwerkersovereenkomst'), ('pentest', 'Pentestrapport'), ('overig', 'Overig')], max_length=25, verbose_name='Type document')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('bestand', models.FileField(upload_to=apps.documenten.models.document_upload_path, verbose_name='Bestand')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('gepubliceerd', 'Gepubliceerd')], default='concept', max_length=15, verbose_name='Status')),
                ('gedeeld_met', models.CharField(choices=[('publiek', 'Publiek'), ('gemeenten', 'Alleen gemeenten'), ('prive', 'Prive')], default='prive', max_length=10, verbose_name='Gedeeld met')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documenten',
                'ordering': ['-aangemaakt_op'],
            },
        ),
    ]
