# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documenten', '0001_initial'),
        ('organisaties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenten', to='organisaties.organisatie', verbose_name='Organisatie'),
        ),
    ]
