# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documenten', '0002_initial'),
        ('pakketten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pakket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenten', to='pakketten.pakket', verbose_name='Pakket'),
        ),
    ]
