apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "softwarecatalogus.fullname" . }}-media
  labels:
    {{- include "softwarecatalogus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
