{{/*
Dit is een template-voorbeeld. In productie worden secrets via
external-secrets-operator of sealed-secrets beheerd.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: softwarecatalogus-secrets
  labels:
    {{- include "softwarecatalogus.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: "VERANDER-DIT-IN-PRODUCTIE"
  POSTGRES_PASSWORD: "VERANDER-DIT-IN-PRODUCTIE"
  POSTGRES_ADMIN_PASSWORD: "VERANDER-DIT-IN-PRODUCTIE"
  POSTGRES_DB: "softwarecatalogus"
  POSTGRES_USER: "swc"
  POSTGRES_HOST: "{{ include "softwarecatalogus.fullname" . }}-postgresql"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://{{ include "softwarecatalogus.fullname" . }}-redis-master:6379/0"
  MEILISEARCH_URL: "http://{{ include "softwarecatalogus.fullname" . }}-meilisearch:7700"
  MEILISEARCH_API_KEY: "VERANDER-DIT-IN-PRODUCTIE"
