# Generated by Django 5.1.15 on 2026-03-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aanbestedingen', '0002_aanbesteding_ef25_status'),
        ('architectuur', '0002_initial'),
        ('organisaties', '0001_initial'),
        ('pakketten', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aanbesteding',
            new_name='aanbestedin_publica_d8bd2e_idx',
            old_name='aanbesteding_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='aanbesteding',
            new_name='aanbestedin_aanbest_c28f60_idx',
            old_name='aanbesteding_dienst_idx',
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='aanbestedende_dienst',
            field=models.CharField(help_text='Naam van de gemeente of organisatie die aanbesteedt', max_length=500, verbose_name='Aanbestedende dienst'),
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='cpv_codes',
            field=models.JSONField(default=list, help_text='Lijst van CPV-codes (Common Procurement Vocabulary)', verbose_name='CPV-codes'),
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='gemma_componenten',
            field=models.ManyToManyField(blank=True, help_text='GEMMA-componenten die relevant zijn voor deze aanbesteding (afgeleid van CPV-codes)', related_name='aanbestedingen', to='architectuur.gemmacomponent', verbose_name='GEMMA componenten'),
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='organisatie',
            field=models.ForeignKey(blank=True, help_text='Gemeente in de Softwarecatalogus die overeenkomt met de aanbestedende dienst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aanbestedingen', to='organisaties.organisatie', verbose_name='Gekoppelde organisatie'),
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='procedure',
            field=models.CharField(blank=True, help_text='Bijv. Openbare procedure, Niet-openbare procedure', max_length=200, verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='publicatiecode',
            field=models.CharField(db_index=True, help_text='Unieke TenderNed publicatiecode (bijv. 2024-545877)', max_length=100, unique=True, verbose_name='Publicatiecode'),
        ),
        migrations.AlterField(
            model_name='aanbesteding',
            name='relevante_pakketten',
            field=models.ManyToManyField(blank=True, help_text='Pakketten in de catalogus die relevant zijn voor deze aanbesteding', related_name='aanbestedingen', to='pakketten.pakket', verbose_name='Relevante pakketten'),
        ),
    ]
