# Generated by Django 5.1.15 on 2026-03-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_118155_idx',
            old_name='core_audit_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_object__42e4a9_idx',
            old_name='core_audit_object_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actie_b33f88_idx',
            old_name='core_audit_actie_idx',
        ),
    ]
