# Generated by Django 5.1.15 on 2026-03-06 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nieuwsbericht',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('samenvatting', models.TextField(max_length=500, verbose_name='Samenvatting')),
                ('inhoud', models.TextField(verbose_name='Inhoud')),
                ('afbeelding', models.ImageField(blank=True, upload_to='nieuws/', verbose_name='Afbeelding')),
                ('gepubliceerd', models.BooleanField(default=False, verbose_name='Gepubliceerd')),
                ('publicatie_datum', models.DateTimeField(blank=True, null=True, verbose_name='Publicatiedatum')),
            ],
            options={
                'verbose_name': 'Nieuwsbericht',
                'verbose_name_plural': 'Nieuwsberichten',
                'ordering': ['-publicatie_datum'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('inhoud', models.TextField(verbose_name='Inhoud')),
                ('gepubliceerd', models.BooleanField(default=False, verbose_name='Gepubliceerd')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': "Pagina's",
                'ordering': ['-aangemaakt_op'],
            },
        ),
    ]
