# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('type', models.CharField(choices=[('gemeente', 'Gemeente'), ('samenwerkingsverband', 'Samenwerkingsverband'), ('leverancier', 'Leverancier'), ('overig', 'Overig')], max_length=25, verbose_name='Type organisatie')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('actief', 'Actief'), ('inactief', 'Inactief')], default='concept', max_length=10, verbose_name='Status')),
                ('oin', models.CharField(blank=True, max_length=20, verbose_name='Organisatie Identificatienummer (OIN)')),
                ('bevoegd_gezag_code', models.CharField(blank=True, max_length=10, verbose_name='Bevoegd gezag code')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Legacy ID (migratie)')),
                ('geregistreerd_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geregistreerde_organisaties', to=settings.AUTH_USER_MODEL, verbose_name='Geregistreerd door')),
            ],
            options={
                'verbose_name': 'Organisatie',
                'verbose_name_plural': 'Organisaties',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Contactpersoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mailadres')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoonnummer')),
                ('functie', models.CharField(blank=True, max_length=255, verbose_name='Functie')),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactpersonen', to='organisaties.organisatie', verbose_name='Organisatie')),
            ],
            options={
                'verbose_name': 'Contactpersoon',
                'verbose_name_plural': 'Contactpersonen',
            },
        ),
    ]
