# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architectuur', '0001_initial'),
        ('organisaties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Koppeling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('type', models.CharField(choices=[('api', 'API'), ('bestand', 'Bestandsuitwisseling'), ('database', 'Database'), ('message_queue', 'Message Queue'), ('anders', 'Anders')], default='api', max_length=15, verbose_name='Type koppeling')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
            ],
            options={
                'verbose_name': 'Koppeling',
                'verbose_name_plural': 'Koppelingen',
            },
        ),
        migrations.CreateModel(
            name='PakketGebruik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('status', models.CharField(choices=[('in_gebruik', 'In gebruik'), ('gepland', 'Gepland'), ('gestopt', 'Gestopt')], default='in_gebruik', max_length=15, verbose_name='Status')),
                ('start_datum', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('eind_datum', models.DateField(blank=True, null=True, verbose_name='Einddatum')),
                ('notitie', models.TextField(blank=True, verbose_name='Notitie')),
            ],
            options={
                'verbose_name': 'Pakketgebruik',
                'verbose_name_plural': 'Pakketgebruik',
                'ordering': ['-aangemaakt_op'],
            },
        ),
        migrations.CreateModel(
            name='Pakket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True, verbose_name='Gewijzigd op')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('versie', models.CharField(blank=True, max_length=50, verbose_name='Versie')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('actief', 'Actief'), ('verouderd', 'Verouderd'), ('ingetrokken', 'Ingetrokken')], default='concept', max_length=15, verbose_name='Status')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('licentievorm', models.CharField(choices=[('commercieel', 'Commercieel'), ('open_source', 'Open source'), ('saas', 'SaaS'), ('anders', 'Anders')], default='commercieel', max_length=15, verbose_name='Licentievorm')),
                ('open_source_licentie', models.CharField(blank=True, help_text='Bijv. EUPL, MIT, GPL', max_length=50, verbose_name='Open source licentie')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('documentatie_url', models.URLField(blank=True, verbose_name='Documentatie URL')),
                ('cloud_provider', models.CharField(blank=True, max_length=100, verbose_name='Cloud provider')),
                ('contactpersoon', models.CharField(blank=True, max_length=255, verbose_name='Contactpersoon')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Legacy ID (migratie)')),
                ('gemma_componenten', models.ManyToManyField(blank=True, related_name='pakketten', through='architectuur.PakketGemmaComponent', to='architectuur.gemmacomponent', verbose_name='GEMMA componenten')),
                ('geregistreerd_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geregistreerde_pakketten', to=settings.AUTH_USER_MODEL, verbose_name='Geregistreerd door')),
                ('leverancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakketten', to='organisaties.organisatie', verbose_name='Leverancier')),
            ],
            options={
                'verbose_name': 'Pakket',
                'verbose_name_plural': 'Pakketten',
                'ordering': ['naam'],
            },
        ),
    ]
