# Generated by Django 5.1.15 on 2026-03-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisaties', '0001_initial'),
        ('pakketten', '0001_initial'),
        ('standaarden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakket',
            name='standaarden',
            field=models.ManyToManyField(blank=True, related_name='pakketten', through='standaarden.PakketStandaard', to='standaarden.standaard', verbose_name='Standaarden'),
        ),
        migrations.AddField(
            model_name='pakketgebruik',
            name='organisatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakketgebruik', to='organisaties.organisatie', verbose_name='Organisatie'),
        ),
        migrations.AddField(
            model_name='pakketgebruik',
            name='pakket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pakketten.pakket', verbose_name='Pakket'),
        ),
        migrations.AddField(
            model_name='koppeling',
            name='naar_pakket_gebruik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koppelingen_naar', to='pakketten.pakketgebruik', verbose_name='Naar pakketgebruik'),
        ),
        migrations.AddField(
            model_name='koppeling',
            name='van_pakket_gebruik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koppelingen_van', to='pakketten.pakketgebruik', verbose_name='Van pakketgebruik'),
        ),
        migrations.AlterUniqueTogether(
            name='pakketgebruik',
            unique_together={('pakket', 'organisatie')},
        ),
    ]
